### ISSUE TITLE
what the dataset do you  train?

### ISSUE THREAD

**Issue by yisampi** [joytsay/livenessDetection#1]
what the dataset do you  train? Thanks.

**Comment by joytsay** [comment]
Hi, dataset was image snapshots from WebCam video of the following footage sequence:
1. footage of high resolution printed photo of me held up to the WebCam (fake)
2. footage of of me (real)
3. footage of iphone held up to WebCam playing video of 2. (fake)

Use use ./gather.bat to get train image snapshots from video in ./videos folder. 
(images will be stored in ./dataset/fake & real)

One might say that training and inference the same person(me) is not objective, 
but I experimented on different people that are not my face with good results.
Due to privacy reasons I cannot provide inference videos on other peoples faces, Thanks.

**Comment by ybdesire** [comment]
@joytsay  Would you share what is the training datatset size ?

**Comment by joytsay** [comment]
> @joytsay Would you share what is the training datatset size ?

Hi recently I trained it for mask detection with the following dataset size:
```
root@94f28c022946:/workspace/FRtraining/livenessDetection/dataset# ls mask | wc -l
9193
root@94f28c022946:/workspace/FRtraining/livenessDetection/dataset# ls unmask | wc -l
9164

```

**Comment by ybdesire** [comment]
Got. Thanks @joytsay for the update.
